# Generated by Django 2.2.4 on 2020-01-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestionar_Usuarios', '0001_initial'),
        ('Gestionar_Informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos_COIP',
            fields=[
                ('Id_Articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('Articulo', models.TextField()),
                ('Inciso', models.TextField()),
                ('Numeral', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Articulos_COIP',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='ContadorInfraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CedulaAgente', models.IntegerField()),
                ('CodigoAgente', models.IntegerField()),
                ('ContadorAgente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.IntegerField()),
                ('Latitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Longitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Ubicacion', models.TextField()),
                ('Fecha_Intento', models.DateField()),
                ('Hora_Intento', models.TimeField()),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Accion', models.IntegerField(blank=True, null=True)),
                ('Agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Usuarios.Agente_Transito')),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion_Transito',
            fields=[
                ('NumeroInfraccion', models.IntegerField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
                ('Ubicacion', models.TextField()),
                ('Latitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Longitud', models.DecimalField(decimal_places=20, max_digits=30)),
                ('Estado', models.CharField(default='Reportado', max_length=20, null=True)),
                ('Fecha_Infraccion', models.DateField()),
                ('Fecha_Registro', models.DateField(auto_now_add=True)),
                ('Hora_Infraccion', models.TimeField()),
                ('Hora_Registro', models.TimeField(auto_now_add=True)),
                ('Agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Usuarios.Agente_Transito')),
                ('ArticuloC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Infraccion.Articulos_COIP')),
                ('Conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Informacion.Conductor')),
                ('Vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Informacion.Vehiculo')),
            ],
            options={
                'verbose_name': 'Infraccion_Transito',
                'verbose_name_plural': 'Infracciones_Transito',
            },
        ),
    ]
