# Generated by Django 2.2.4 on 2020-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Infraccion', '0002_auto_20200122_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraccion_transito',
            name='Valor',
        ),
        migrations.AddField(
            model_name='infraccion_transito',
            name='Hora_Detencion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
