# Generated by Django 2.2.4 on 2020-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('Id_Evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('Foto', models.FileField(blank=True, default=None, null=True, upload_to='imagenes/')),
                ('Audio', models.FileField(blank=True, default=None, null=True, upload_to='audio/')),
                ('Video', models.FileField(blank=True, default=None, null=True, upload_to='videos/')),
                ('CodigoInfraccion', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencia',
            },
        ),
        migrations.CreateModel(
            name='MyAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_aud', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('id_Evidencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.FileField(blank=True, null=True, upload_to='imagenes/')),
                ('id_Evidencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_vid', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('id_Evidencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
