# Generated by Django 2.2.4 on 2020-01-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Evidencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evidencia',
        ),
    ]
