# Generated by Django 2.2.4 on 2020-01-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Evidencia', '0002_delete_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='id_Evidencia',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myimage',
            name='model_pic',
            field=models.FileField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
