# Generated by Django 2.2.4 on 2020-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('CedulaC', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('TipoLicencia', models.CharField(max_length=20)),
                ('CategoriaLicencia', models.CharField(max_length=20)),
                ('FechaEmisionLicencia', models.DateField()),
                ('FechaCaducidadLicencia', models.DateField()),
                ('Puntos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('Placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=20)),
                ('FechaMatricula', models.DateField()),
                ('FechaCaducidadMatricula', models.DateField()),
            ],
        ),
    ]
