# Generated by Django 2.2.4 on 2020-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Accidente', '0002_contadoraccidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidente_transito',
            name='Latitud',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accidente_transito',
            name='Longitud',
            field=models.DecimalField(decimal_places=20, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
