# Generated by Django 2.2.4 on 2020-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Codigo_Admin', models.IntegerField()),
                ('Nombres', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Agente_Transito',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Codigo_Agente', models.IntegerField()),
                ('Nombres', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=20)),
                ('fotoA', models.FileField(upload_to='imagenes/')),
            ],
            options={
                'verbose_name': 'Agente_Transito',
                'verbose_name_plural': 'Agente de transito',
            },
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('Cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('Codigo_Juez', models.IntegerField()),
                ('Nombres', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Juez',
                'verbose_name_plural': 'Juez',
            },
        ),
        migrations.CreateModel(
            name='NumeroInfraccion',
            fields=[
                ('Id_numeroInfraccion', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroInfraccion', models.IntegerField()),
                ('Codigo_Agente', models.IntegerField()),
            ],
        ),
    ]
