# Generated by Django 2.2.4 on 2020-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_transito',
            name='fotoA',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
